---
name: Validate and Release Terraform Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
      release-message:
        required: true
        type: string

jobs:
  Release-Terraform:
    if: github.event.ref == 'refs/heads/main'
    name: Release
    needs: Validate-Terraform
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-release-module.yaml@main  
    with:
      module-name: flux2-cluster-bootstrap
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      runs-on: ghr-flux2-cluster-bootstrap-labda-test
      continue-error: false
