---
name: Terraform
on:
  push:
    branches:
      - main
      - feature/*
      - review/*
      - fix/*
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  validate-terraform:
    if: github.event.ref == 'refs/heads/main'
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-flux2-cluster-bootstrap-labda-test
      terraform-version: 1.8.4
      tflint-version: v0.51.1
      continue-error: false
